Optional log details
j256/ormlite-core pull request #204
Opened 2021-05-10 15:34 UTC by PeachesMLG

Made logging details optional

2021-05-13 10:00 UTC, noordawod commented on src/main/java/com/j256/ormlite/table/TableUtils.java
> +											 boolean ifNotExists, boolean logDetails) throws SQLException {
Your IDE is set to insert tabs, please fix this line.

2021-05-13 10:03 UTC, noordawod requested changes
Thanks for the pr. All in all it looks okay, few cosmetic changes required though.

2021-05-13 10:03 UTC, noordawod commented on src/main/java/com/j256/ormlite/table/TableUtils.java
> +									boolean ignoreErrors, boolean returnsNegative, boolean expectingZero, boolean logDetails) throws SQLException {
Too many tabs here.

2021-05-13 10:03 UTC, noordawod commented on src/main/java/com/j256/ormlite/table/TableUtils.java
> +											 boolean ifNotExists, boolean logDetails) throws SQLException {
Too many tabs here.

2021-05-13 10:03 UTC, noordawod commented on src/main/java/com/j256/ormlite/table/TableUtils.java
> +				if(logDetails) {
Insert a space before the opening brace.

2021-05-16 13:33 UTC, j256 commented
I'm curious why this is necessary?  Is this more about too much log output or what?

2021-05-16 21:04 UTC, PeachesMLG commented
> I'm curious why this is necessary? Is this more about too much log output or what?

Ye basically, Im coding a java program that uses this and people have asked if its possible that it doesnt show the creation commands since i have like 15 tables and it spams the console a bit

2021-05-16 21:19 UTC, PeachesMLG commented
Although I just realised in your latest commit you added setLogBackendType so I can just do setLogBackendType(LogBackendType.NULL)

Unfortunatly this hasn been released to maven central yet, when do you plan on posting that new version?

2021-05-16 21:21 UTC, PeachesMLG commented
Guess ill hoest the repo myself until you release it :) Thanks

2021-05-16 21:21 UTC, closed without merging